#!/usr/bin/env python3
"""Inspect vocabulary TFRecord files generated by the dataset_maker_main.

This tool inspects vocabulary files which contain Vocab protos with feature names
and their associated token vocabularies.
"""

import sys
import tensorflow as tf
from typing import Dict, Set
import argparse

# Add the facade root directory to the path for protos
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from protos import vocab_pb2


def inspect_vocab_file(file_path: str, show_tokens: int = 10, feature_filter: str = None) -> None:
    """Inspect a vocabulary TFRecord file.
    
    Args:
        file_path: Path to the vocabulary TFRecord file
        show_tokens: Number of tokens to display per feature (0 = none, -1 = all)
        feature_filter: Only show features containing this substring
    """
    print(f"Inspecting Vocabulary TFRecord file: {file_path}")
    print("=" * 60)
    
    try:
        dataset = tf.data.TFRecordDataset(file_path)
        
        context_features = {}
        sequence_features = {}
        total_records = 0
        
        print("Scanning vocabulary file...")
        
        for raw_record in dataset:
            vocab = vocab_pb2.Vocab()
            vocab.ParseFromString(raw_record.numpy())
            total_records += 1
            
            # Apply feature filter if specified
            if feature_filter and feature_filter.lower() not in vocab.name.lower():
                continue
            
            feature_dict = context_features if vocab.is_context else sequence_features
            feature_dict[vocab.name] = list(vocab.values)
        
        print(f"Total vocabulary records found: {total_records}")
        print()
        
        # Display context features
        if context_features:
            print("CONTEXT FEATURES:")
            print("-" * 40)
            for i, (feature_name, tokens) in enumerate(sorted(context_features.items()), 1):
                print(f"{i:2d}. {feature_name} ({len(tokens)} tokens)")
                
                if show_tokens > 0:
                    tokens_to_show = tokens[:show_tokens] if show_tokens != -1 else tokens
                    for j, token in enumerate(tokens_to_show):
                        try:
                            # Try to decode as UTF-8 string
                            decoded = token.decode('utf-8')
                            print(f"    {j+1:3d}: '{decoded}'")
                        except UnicodeDecodeError:
                            # Show as hex if not valid UTF-8
                            hex_str = token.hex()
                            print(f"    {j+1:3d}: {hex_str} (hex)")
                    
                    if show_tokens != -1 and len(tokens) > show_tokens:
                        print(f"    ... and {len(tokens) - show_tokens} more tokens")
                
                print()
        
        # Display sequence features  
        if sequence_features:
            print("SEQUENCE FEATURES:")
            print("-" * 40)
            for i, (feature_name, tokens) in enumerate(sorted(sequence_features.items()), 1):
                print(f"{i:2d}. {feature_name} ({len(tokens)} tokens)")
                
                if show_tokens > 0:
                    tokens_to_show = tokens[:show_tokens] if show_tokens != -1 else tokens
                    for j, token in enumerate(tokens_to_show):
                        try:
                            # Try to decode as UTF-8 string
                            decoded = token.decode('utf-8')
                            print(f"    {j+1:3d}: '{decoded}'")
                        except UnicodeDecodeError:
                            # Show as hex if not valid UTF-8
                            hex_str = token.hex()
                            print(f"    {j+1:3d}: {hex_str} (hex)")
                    
                    if show_tokens != -1 and len(tokens) > show_tokens:
                        print(f"    ... and {len(tokens) - show_tokens} more tokens")
                
                print()
        
        # Summary
        print("SUMMARY:")
        print("-" * 40)
        print(f"Total records: {total_records}")
        print(f"Context features: {len(context_features)}")
        print(f"Sequence features: {len(sequence_features)}")
        
        if feature_filter:
            print(f"Filtered by: '{feature_filter}'")
        
        # Check for expected context features based on current configuration
        expected_context_features = [
            "calendar/meeting_f/t",
            "calendar/meeting_b/t", 
            "team/team_member_u/t",
            "job_title/title_peer_u/t"
        ]
        
        for expected in expected_context_features:
            if expected not in context_features:
                print(f"\n⚠️  WARNING: Expected context feature '{expected}' not found!")
        
        # Check for expected action features (simple /prin/t pattern)
        expected_actions = [
            "gdrive_doc_access/prin/t"
        ]
        
        for expected in expected_actions:
            if expected not in sequence_features:
                print(f"⚠️  WARNING: Expected sequence feature '{expected}' not found!")
        
        # Check for any unexpected event-specific features (should not exist after rollback)
        event_specific_features = [
            "gdrive_doc_access/edit/t",
            "gdrive_doc_access/view/t", 
            "gdrive_doc_access/download/t",
            "gdrive_doc_access/create/t"
        ]
        
        for event_feature in event_specific_features:
            if event_feature in sequence_features:
                print(f"⚠️  NOTICE: Found event-specific feature '{event_feature}' (rollback may be incomplete)")
            
    except Exception as e:
        print(f"Error reading vocabulary file: {e}")
        return


def main():
    parser = argparse.ArgumentParser(description='Inspect vocabulary TFRecord files')
    parser.add_argument('file_path', help='Path to the vocabulary TFRecord file')
    parser.add_argument('--tokens', '-t', type=int, default=10, 
                       help='Number of tokens to show per feature (0=none, -1=all, default=10)')
    parser.add_argument('--filter', '-f', type=str, default=None,
                       help='Only show features containing this substring')
    
    args = parser.parse_args()
    
    inspect_vocab_file(args.file_path, args.tokens, args.filter)


if __name__ == '__main__':
    main()
